# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install latex
        run: |
          sudo apt-get update -y

          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          sudo apt-get install -y texlive-bibtex-extra biber
      #    sudo apt-get install texlive-full
      # sudo apt-get install texmaker
          

      # Runs a set of commands using the runners shell
      - name: build CV
        run: |
          pdflatex cv-llt.tex
          biber cv-llt
          pdflatex cv-llt.tex
      
      - name: git push result
        run : | 
          git config --global user.email "khatiri.med@gmail.com"
          git config --global user.name "Mohammed khatiri"
          git add dcv-llt.tex
          git commit -m "new pdf cv from git"
          git push
